site_name: Home Recipes
site_url: https://recipes.shadmanhabib.com
repo_url: https://github.com/shadmanhabib/home-recipes
repo_name: shadmanhabib/home-recipes

theme: 
  name: material
  features:
    - navigation.instant
    - naviagtion.instant.prefetch
    - navigation.sections
    - navigation.indexes
    #- navigation.expand
    #- navigation.tabs
    #- toc.follow
    #- toc.integrate
    - navigation.path
    - search.suggest

nav:
  - 'index.md'
  - 1. Curry:
    - '01-curry/index.md'
    - '01-curry/vegetables.md'
    - '01-curry/meat.md'
    - '01-curry/poultry.md'
    - '01-curry/fish.md'
    - '01-curry/lentil.md'
    - '01-curry/rice & bread.md'
    - '01-curry/desserts.md'
    - '01-curry/drinks.md'
    - '01-curry/snacks.md'
    - '01-curry/relishes.md'